<?
if ($this->page_id > 0) {
    $page = new CMS_Content_Item_Page($this->page_id);
    $pageName = $page->name;
} else {
    $page = null;
}
?>
<tr>
    <td class="links">
        <a href="/menuitem/update/id/<?=$this->id?>">Atualizar</a>
    </td>
    <td>
        <a href="/menuitem/move/direction/up/id/<?=$this->id?>"><img src="/skins/brown/images/main_container/up_icon.png" alt="Mover para cima"></img></a>
    </td>
    <td>   
        <a href="/menuitem/move/direction/down/id/<?=$this->id?>"><img src="/skins/brown/images/main_container/down_icon.png" alt="Mover para baixo"></img></a>
    </td>
    <td>
        <a href="/menuitem/delete/id/<?=$this->id?>"><img src="/skins/brown/images/main_container/delete_icon.png" alt="Excluir"></img></a>
    </td>
    <td><?=$this->label?></td>
    <td><?=$this->pageName?></td>
    <td><?=$this->link?></td>
</tr>