<h2>Lista de Erros</h2>
<?php 
//Zend_Debug::dump($this,null,true);
?>
<?//=$this->pagina?>
<?=$this->listToolsForm?>

<?=$this->paginationControl($this->paginator,'Sliding','partials/pagination-control.phtml');?>
<table class='spreadsheet' cellspacing='0'>
    <tr>
         <th>&nbsp;</th>
         <th>Data</th>
         <th>Prioridade</th>
         <th>Estado</th>
         <th>URL</th>
         <th>Autor</th>
         <th>Descrição</th>
    </tr>
    <?=$this->partialLoop('bug/list_table-row.phtml', $this->paginator)?>
</table>
