
  <h1>ERRO</h1>
  <h2 style="color: #F00"><?=$this->message ?></h2>
  <h2>
  Você pode reportar o erro <a href="/bug/submit">clicando aqui</a>, <br />
  Ou entre em contato <a href="/contact">clicando aqui</a>
  </h2>
  <? if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?=$this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?=$this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?=var_export($this->request->getParams(), true) ?>
  </pre>
  <? endif ?>

