<h2>Site em Constru&ccedil;&atilde;o.</h2>
<p>&nbsp;&nbsp;Como é possível notar, este site está em processo de constru&ccedil;&atilde;o, por enquanto fique com um vídeo de um sistema em produção que a equipe Mackenzie Brasília está fazendo!</p>
                               
                                <div id="video" style="width: 640px; text-align: justify;">
                                
                                <object type="application/x-shockwave-flash" data="http://www.youtube.com/v/k4a9YhxJxmk&amp;hl=en_US&amp;fs=1&amp;rel=0&amp;color1=0x3a3a3a&amp;color2=0x999999" width="400" height="326">
                                <param name="movie" value="http://www.youtube.com/v/k4a9YhxJxmk&amp;hl=en_US&amp;fs=1&amp;rel=0&amp;color1=0x3a3a3a&amp;color2=0x999999" />
                                <param name="FlashVars" value="playerMode=embedded" />
                                </object>

                                <!-- <object width="640" height="385"><param name="movie" value="http://www.youtube.com/v/k4a9YhxJxmk&hl=en_US&fs=1&rel=0&color1=0x3a3a3a&color2=0x999999"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/k4a9YhxJxmk&hl=en_US&fs=1&rel=0&color1=0x3a3a3a&color2=0x999999" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="640" height="385"></embed></object>-->

                                <!-- <div style="width:640px;height:385px;" id="player"></div> -->

                                </div>
                                