<h2>Gerenciar itens do Menu</h2>
<? if ($this->items != null) : ?>
<table class="spreadsheet">
    <tr>
        <th colspan="4">Ações</th>
        <th>Rótulos</th>
        <th>Página</th>
        <th>Link</th>
    </tr>
    <?=$this->partialLoop('partials/_menuitem-row.phtml',$this->items) ?>
</table>
<? else: ?>
<p>Este menu ainda não possui itens.</p>
<? endif; ?>
<p><a href="/menuitem/add/menu/<?=$this->menu->id?>">Adicionar novo item</a></p>