<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();

$this->layout()->nav = $this->action('render','menu',null,array('menu'=>$this->mainMenuId));
$this->layout()->adminMenu = $this->action('render','menu',null,array('menu'=>$this->adminMenuId));
$this->layout()->userForm = $this->action('index','user');
$searchForm = new Form_SearchForm();
$searchForm->setAction('/search');
$this->layout()->searchForm = $searchForm;
?>
<html xmlns="http://www.w3.org/1999/xhtml" >
    <head>
    
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
        <meta name="google-site-verification" content="jTk084YZmt0uZehdXiIG-kmnIfmt_kMk4b3d29Dm_O0" />
        <?php
        echo $this->headTitle();
        
        $this->loadSkin($this->skin);
        echo $this->headLink();
        
        $this->headScript()->appendFile($this->baseUrl() . '/util/js/jqt.1.2.1.min.js');
        $this->headScript()->appendFile($this->baseUrl() . '/util/js/flowplayer-3.2.0.min.js');
        $this->headScript()->appendFile($this->baseUrl() . '/util/js/main_functions.js');
        echo $this->headScript();
        ?>
        
    </head>

    <body>
        <div id="page">
            <div id="controllers_container"></div>
            <div id="main_container">
                <div id="header">
                    <div id="top">
                        <div class="left"></div>
                        <div class="right"></div>
                    </div>
                    <div class="content">
                        <div class="left"></div>
                        <div class="menu" id="main">
                            <?=$this->layout()->nav?>
                        </div>
                        <div class="menu" id="admin">
                            <?=$this->layout()->adminMenu?>
                        </div>
                        <div id="login">
                            <?=$this->layout()->userForm?>
                        </div>
                        <div class="right" onClick="javascript:animateLoginAction('auto');"></div> 
                    </div>  
                </div>
                <div id="center">
                    <div class="content">
                        <div class="left"></div>
                            <div class="middle">
                            
                                <div id="info" style="width: 640px; text-align: justify;">
                                <?=$this->layout()->content?>
                                </div>
                                

                                
                            </div>
                        <div id="search">
                            <?=$this->layout()->searchForm?>
                        </div>
                        <div class="right"></div> 
                    </div>  
                </div>
                <div id="footer">
                    <div class="content">
                        <div class="left"></div>
                        <div class="middle">
                            contato@renatomefi.com.br
                        </div>
                        <div class="right"></div> 
                    </div>
                    <div id="bottom">
                        <div class="left"></div>
                        <div class="right"></div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>